### ISSUE TITLE
Fix crash to create thread

### ISSUE THREAD

**Issue by coldev** [arcadenea/fake_mixer#1]
Thanks for your  DC  Library...

SOLUTION to crash (reset DC)

replace in fake_mixer.c  , use sdl thread to fix crash...

//=====================================
static int *snd_thread_sdl(void *data)
{

	for(;;)
	{

		MikMod_Update();

		thd_sleep(5);
	}

	return NULL;
}

int Mix_OpenAudio(int frequency, uint16 format, int channels, int chunksize)
{
    /* register all the drivers */
    MikMod_RegisterAllDrivers();

    /* register all the module loaders */
    MikMod_RegisterAllLoaders();

    /* initialize the library */
    md_mode |= DMODE_SOFT_MUSIC | DMODE_SOFT_SNDFX;

    if (MikMod_Init("")) {
        printf("Could not initialize sound, reason: %s\n", MikMod_strerror(MikMod_errno));
		return 1;
    }

 
    /* One for music and one for sfx */
    MikMod_SetNumVoices(-1,8);
    MikMod_EnableOutput();
 
    loaded = 1;
	gfrequency = frequency;
	gchannels = channels;
 
//	thd_create(0, snd_thread, NULL);  //crash runtime

     SDL_CreateThread(snd_thread_sdl, "TestThread", (void *)NULL);

 
	return 0;
}

//=====================================

**Comment by arcadenea** [comment]
thanks for your solution, will test it and add into the source. Some questions about it:
What version of kos are you using?
Do you have some test code to trigger the crash?
